"""Bind a static list of stopwords from nltk.corpus.stopowrds, to avoid reparsing the corpora and importing nltk."""

stopwords = {'a', 'about', 'above', 'across', 'after', 'afterwards', 'again', 'against', 'ago', 'all', 'almost',
             'alone', 'along', 'already', 'also', 'although', 'always', 'am', 'among', 'amongst', 'amount', 'an', 'and',
             'another', 'any', 'anyhow', 'anyone', 'anything', 'anyway', 'anywhere', 'are', 'around', 'as', 'at',
             'back', 'be', 'became', 'because', 'become', 'becomes', 'becoming', 'been', 'before', 'beforehand',
             'behind', 'being', 'below', 'beside', 'besides', 'between', 'beyond', 'bill', 'both', 'bottom', 'but',
             'by', 'call', 'can', 'cannot', 'cant', 'co', 'computer', 'con', 'consist', 'could', 'couldnt', 'cry',
             'de', 'describe', 'detail', 'do', 'done', 'down', 'due', 'during', 'each', 'eg', 'eight', 'either',
             'eleven', 'else', 'elsewhere', 'empty', 'enough', 'etc', 'etc.', 'even', 'ever', 'every', 'everyone',
             'everything', 'everywhere', 'except', 'few', 'fifteen', 'fifty', 'fill', 'find', 'fire', 'fig.',
             'first', 'five', 'for', 'former', 'formerly', 'forty', 'found', 'four', 'from', 'front', 'full',
             'further', 'get', 'give', 'go', 'had', 'has', 'hasnt', 'have', 'he', 'hence', 'her', 'here', 'hereafter',
             'hereby', 'herein', 'hereupon', 'hers', 'herself', 'him', 'himself', 'his', 'how', 'however', 'hundred',
             'i', 'ie', 'if', 'in', 'inc', 'indeed', 'interest', 'into', 'is', 'it', 'its', 'itself', 'keep', 'last',
             'latter', 'latterly', 'least', 'less', 'ltd', 'made', 'many', 'may', 'me', 'meanwhile', 'might', 'mill',
             'mine', 'more', 'moreover', 'most', 'mostly', 'move', 'much', 'must', 'my', 'myself', 'name', 'namely',
             'neither', 'never', 'nevertheless', 'next', 'nine', 'no', 'nobody', 'none', 'noone', 'nor', 'not', "n't",
             'nothing', 'now', 'nowhere', 'of', 'off', 'often', 'on', 'once', 'one', "one's", 'only', 'onto', 'or',
             'other', 'others', 'otherwise', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 'part', 'per', 'perhaps',
             'please', 'put', 'rather', 're', 'same', 'see', 'seem', 'seemed', 'sb', 'sb.', 'seeming', 'seems',
             'serious', 'several', 'she', 'should', 'show', 'side', 'since', 'sincere', 'six', 'sixty', 'so',
             'some', 'somehow', 'someone', 'something', 'sometime', 'sometimes', 'somewhere', 'st', 'st.', 'still',
             'such', 'system', 'take', 'ten', 'than', 'that', 'the', 'their', 'them', 'themselves', 'then', 'thence',
             'there', 'thereafter', 'thereby', 'therefore', 'therein', 'thereupon', 'these', 'they', 'thick', 'thin',
             'third', 'this', 'those', 'though', 'three', 'through', 'throughout', 'thru', 'thus', 'to', 'together',
             'too', 'top', 'toward', 'towards', 'twelve', 'twenty', 'two', 'un', 'under', 'until', 'up', 'upon',
             'us', 'use', 'very', 'via', 'was', 'we', 'well', 'were', 'what', 'whatever', 'when', 'whence', 'whenever',
             'where', 'whereafter', 'whereas', 'whereby', 'wherein', 'whereupon', 'wherever', 'whether', 'which',
             'while', 'whither', 'who', 'whoever', 'whole', 'whom', 'whose', 'why', 'will', 'with', 'within', 'without',
             'would', 'yet', 'you', 'your', 'yours', 'yourself', 'yourselves', 'quality', 'event', 'action',
             'activity', 'form', 'thing', 'place', 'particular', 'certain', 'form', 'cause', 'state', 'animal',
             'people', 'group', 'person', 'body', 'act', 'make', 'object', 'time', 'various', 'large', 'big',
             'purpose', 'process', 'small', 'little'}

abbreviations = {'A.', 'A.A.A.', 'A.B.', 'A.B.A.', 'A.C.', 'A.D.', 'A.D.C.', 'A.F.', 'A.F.A.M.', 'A.G.', 'A.H.', 'A.I.',
                 'A.I.A.', 'A.I.D.', 'A.L.', 'A.L.P.', 'A.M.', 'A.M.A.', 'A.M.D.G.', 'A.N.', 'a.p.', 'a.r.', 'A.R.C.S.',
                 'A.U.', 'A.U.C.', 'A.V.', 'a.w.', 'A.W.O.L.', 'abl.', 'abr.', 'acc.', 'accel.', 'acct.', 'acpt.',
                 'actg.', 'add.', 'adj.', 'adjt.', 'Adm.', 'adv.', 'advt.', 'ae.', 'aeron.', 'aet.', 'Af.', 'agcy.',
                 'agr.', 'agric.', 'agron.', 'al.', 'Ala.', 'Alas.', 'Alb.', 'Ald.', 'Alg.', 'alk.', 'alt.', 'Alta.',
                 'alum.', 'Am.', 'Amer.', 'amp.', 'amt.', 'an.', 'anal.', 'anat.', 'Angl.', 'anim.', 'ann.', 'anon.',
                 'ant.', 'anthrop.', 'anthropol.', 'antiq.', 'Apoc.', 'app.', 'approx.', 'Apr.', 'apt.', 'Ar.', 'Arab.',
                 'Arch.', 'archaeol.', 'archit.', 'archt.', 'Arg.', 'Ariz.', 'Ark.', 'Arm.', 'arr.', 'art.', 'Assyr.',
                 'assn.', 'assoc.', 'asst.', 'astr.', 'astrol.', 'at.', 'atm.', 'att.', 'atty.', 'attrib.', 'aud.',
                 'Aug.', 'Aus.', 'Aust.', 'Austral.', 'auth.', 'auto.', 'aux.', 'av.', 'avdp.', 'Ave.', 'avg.', 'avn.',
                 'avoir.', 'ax.', 'B.A.', 'B.A.A.', 'B.Arch.', 'B.B.C.', 'B.C.', 'B.C.E.', 'B.C.L.', 'B.Ch.', 'B.D.',
                 'B.D.S.', 'B.E.', 'B.E.F.', 'B.E.M.', 'B.Ed.', 'b.f.', 'B.L.', 'B.Litt.', 'B.M.', 'B.Mus.', 'B.O.',
                 'B.O.D.', 'B.P.', 'B.Phil.', 'B.R.C.S.', 'B.S.', 'B.S.S.', 'B.Sc.', 'B.T.U.', 'B.V.', 'B.V.M.',
                 'bact.', 'bacteriol.', 'bal.', 'Balt.', 'bar.', 'barit.', 'Bart.', 'bbl.', 'bd.', 'bdl.', 'Belg.',
                 'Beng.', 'bet.', 'Bib.', 'Bibl.', 'bibliog.', 'biog.', 'biol.', 'Byz.', 'bk.', 'bkcy.', 'bkg.', 'bks.',
                 'bl.', 'bldg.', 'blk.', 'Bn.', 'Bol.', 'bor.', 'bot.', 'bp.', 'Br.', 'Braz.', 'Brig.', 'Brit.',
                 'bros.', 'Bt.', 'btl.', 'btry.', 'bu.', 'bul.', 'Bulg.', 'bull.', 'Bur.', 'bus.', 'bx.', 'C.', 'C.A.',
                 'C.A.F.', 'C.B.', 'C.B.D.', 'C.B.E.', 'C.C.', 'C.D.', 'C.E.', 'C.F.', 'C.G.', 'c.h.', 'C.I.', 'C.I.O.',
                 'c.m.', 'C.M.G.', 'C.O.', 'C.O.D.', 'C.P.', 'C.R.', 'C.S.', 'C.T.', 'C.V.O.', 'c.w.o.', 'ca.', 'Cal.',
                 'Calif.', 'Camb.', 'Can.', 'Canad.', 'canc.', 'Cant.', 'cap.', 'caps.', 'Capt.', 'Card.', 'cat.',
                 'Cath.', 'caus.', 'Cav.', 'cc.', 'cd.', 'Cdr.', 'Celt.', 'cen.', 'cent.', 'cert.', 'cf.', 'cg.', 'ch.',
                 'Ch.B.', 'Ch.E.', 'chap.', 'chem.', 'chg.', 'Chin.', 'chm.', 'Chr.', 'Chron.', 'chs.', 'cyl.', 'cir.',
                 'cit.', 'civ.', 'cl.', 'class.', 'Cmdr.', 'cml.', 'Co.', 'cog.', 'Col.', 'coll.', 'collat.', 'colloq.',
                 'Colo.', 'Com.', 'comb.', 'comdg.', 'Comdr.', 'Comdt.', 'comm.', 'comp.', 'compar.', 'Comr.', 'Con.',
                 'conc.', 'conf.', 'Cong.', 'conj.', 'Conn.', 'Cons.', 'constr.', 'cont.', 'contd.', 'contemp.',
                 'contr.', 'contrib.', 'coop.', 'Cor.', 'corp.', 'corr.', 'correl.', 'cp.', 'cpd.', 'cr.', 'crim.',
                 'cryst.', 'crit.', 'cs.', 'ct.', 'ctr.', 'cts.', 'cur.', 'cwt.', 'Czech.', 'D.', 'D.A.', 'D.B.E.',
                 'D.C.', 'D.C.L.', 'D.C.M.', 'D.D.', 'D.D.S.', 'D.Eng.', 'D.F.', 'D.F.C.', 'D.J.', 'D.O.', 'D.O.A.',
                 'D.O.M.', 'D.P.', 'D.P.H.', 'D.P.W.', 'D.S.', 'D.S.C.', 'D.S.M.', 'D.S.O.', 'D.Sc.', 'D.V.', 'D.V.M.',
                 'd.w.t.', 'Dak.', 'Dan.', 'dat.', 'dbl.', 'dd.', 'deb.', 'Dec.', 'decd.', 'decl.', 'decresc.', 'def.',
                 'deg.', 'Del.', 'Dem.', 'Den.', 'denom.', 'dent.', 'dep.', 'dept.', 'der.', 'deriv.', 'desc.', 'Deut.',
                 'di.', 'diag.', 'dial.', 'diam.', 'dict.', 'diff.', 'dig.', 'dim.', 'Din.', 'dipl.', 'dir.', 'disc.',
                 'dist.', 'distr.', 'div.', 'dk.', 'dlr.', 'dlvy.', 'do.', 'doc.', 'dol.', 'Dom.', 'doz.', 'dpt.',
                 'Dr.', 'Du.', 'dup.', 'Dur.', 'dz.', 'E.', 'E.E.', 'e.g.', 'E.I.', 'e.o.', 'e.o.m.', 'E.R.', 'E.T.A.',
                 'E.T.D.', 'E.V.', 'ea.', 'eccl.', 'Ecclus.', 'ecol.', 'econ.', 'Ecua.', 'ed.', 'edit.', 'educ.', 'Eg.',
                 'elect.', 'elem.', 'Eliz.', 'embryol.', 'Emp.', 'enc.', 'ency.', 'encl.', 'Eng.', 'engin.', 'engr.',
                 'enl.', 'Ens.', 'entomol.', 'Ep.', 'Eph.', 'Epiph.', 'Epis.', 'eq.', 'equiv.', 'Esd.', 'esp.', 'Esq.',
                 'est.', 'Esth.', 'etc.', 'Eth.', 'ethnol.', 'Eur.', 'Ex.', 'Exc.', 'exch.', 'excl.', 'exec.', 'Exod.',
                 'exp.', 'exr.', 'ext.', 'Ez.', 'Ezek.', 'f.', 'F.A.M.', 'F.A.S.', 'F.B.A.', 'f.c.', 'F.D.', 'F.I.',
                 'F.O.', 'f.o.b.', 'F.P.', 'f.p.s.', 'f.s.', 'f.v.', 'F.Z.S.', 'fac.', 'fam.', 'fath.', 'Feb.', 'fec.',
                 'Fed.', 'fem.', 'ff.', 'fig.', 'Fin.', 'Fl.', 'Fla.', 'fld.', 'Flem.', 'flor.', 'fm.', 'fo.', 'fol.',
                 'foll.', 'for.', 'fort.', 'Fr.', 'freq.', 'Fri.', 'Fris.', 'Frs.', 'frt.', 'ft.', 'fth.', 'fur.',
                 'fut.', 'fwd.', 'G.', 'G.A.', 'G.A.R.', 'G.B.', 'G.B.E.', 'G.C.B.', 'G.C.F.', 'G.C.M.', 'G.H.Q.',
                 'G.I.', 'G.M.', 'G.O.', 'G.O.P.', 'G.P.', 'G.P.O.', 'G.P.U.', 'G.S.', 'g.u.', 'g.v.', 'Ga.', 'Gal.',
                 'gaz.', 'gds.', 'Gen.', 'geneal.', 'genit.', 'Genl.', 'geod.', 'geog.', 'geol.', 'geom.', 'Ger.',
                 'gi.', 'gl.', 'gloss.', 'glt.', 'Goth.', 'Gov.', 'Govt.', 'Gr.', 'gram.', 'gro.', 'gt.', 'gtd.',
                 'guar.', 'Guat.', 'Guin.', 'h.', 'h.a.', 'H.C.', 'H.C.F.', 'H.H.', 'H.I.', 'H.I.H.', 'H.M.', 'H.M.S.',
                 'H.P.', 'H.Q.', 'H.R.', 'H.R.H.', 'h.s.', 'H.S.H.', 'H.S.M.', 'H.V.', 'Hab.', 'Hag.', 'hd.', 'hdqrs.',
                 'Heb.', 'her.', 'herp.', 'hf.', 'hgt.', 'Hind.', 'hyp.', 'hypoth.', 'hist.', 'Hond.', 'hor.', 'horol.',
                 'hort.', 'Hos.', 'hosp.', 'hr.', 'ht.', 'Hung.', 'i.', 'Y.', 'I.C.', 'I.C.S.', 'I.D.', 'i.e.',
                 'I.F.S.', 'I.M.', 'Y.M.C.A.', 'Y.M.H.A.', 'I.N.D.', 'I.O.O.F.', 'i.q.', 'I.R.A.', 'Y.T.', 'I.T.U.',
                 'I.V.', 'Y.W.C.A.', 'Y.W.H.A.', 'I.W.W.', 'Ia.', 'ib.', 'ibid.', 'Ice.', 'Icel.', 'ichthyol.', 'id.',
                 'ign.', 'Ill.', 'illust.', 'imit.', 'Imp.', 'imper.', 'imperf.', 'impers.', 'impf.', 'impv.', 'in.',
                 'Inc.', 'incl.', 'incr.', 'Ind.', 'indef.', 'indic.', 'induc.', 'Inf.', 'infin.', 'init.', 'inorg.',
                 'ins.', 'insp.', 'inst.', 'instr.', 'int.', 'intens.', 'inter.', 'interj.', 'internat.', 'interrog.',
                 'intr.', 'intrans.', 'intro.', 'inv.', 'invt.', 'Ir.', 'Iran.', 'Ire.', 'irreg.', 'yrs.', 'Is.',
                 'Isth.', 'Ital.', 'Yugo.', 'J.', 'J.A.', 'J.A.G.', 'J.C.', 'J.C.D.', 'J.C.L.', 'J.C.S.', 'J.D.',
                 'J.P.', 'J.S.D.', 'J.W.V.', 'Ja.', 'Jam.', 'Jan.', 'Jap.', 'Jas.', 'Jav.', 'jct.', 'Jer.', 'JJ.',
                 'Josh.', 'jour.', 'Jr.', 'Jud.', 'Jul.', 'Jun.', 'jurisp.', 'K.', 'K.B.E.', 'K.C.B.', 'K.C.M.G.',
                 'K.C.V.O.', 'K.G.', 'K.K.K.', 'K.O.', 'K.P.', 'K.T.', 'K.V.', 'Kans.', 'kg.', 'Ky.', 'kl.', 'km.',
                 'kn.', 'Knt.', 'kr.', 'Kt.', 'L.', 'L.A.', 'l.c.', 'L.C.L.', 'L.D.S.', 'l.h.', 'L.I.', 'L.P.',
                 'L.S.D.', 'l.t.', 'La.', 'Lab.', 'Lam.', 'lang.', 'Lat.', 'lb.', 'Ld.', 'lea.', 'lect.', 'leg.',
                 'Lev.', 'Levit.', 'lex.', 'lexicog.', 'lg.', 'lgth.', 'Lib.', 'Lieut.', 'lin.', 'ling.', 'liq.',
                 'lit.', 'Lith.', 'litho.', 'lithol.', 'll.', 'LL.B.', 'LL.D.', 'LL.M.', 'loq.', 'Lt.', 'Ltd.', 'Luth.',
                 'Lux.', 'lv.', 'M.', 'M.A.', 'M.Arch.', 'M.B.', 'M.B.A.', 'M.B.E.', 'M.C.', 'M.D.', 'M.E.', 'M.Ed.',
                 'M.I.A.', 'M.M.', 'm.m.f.', 'M.O.', 'M.P.', 'M.P.S.', 'M.S.', 'm.s.l.', 'M.Sc.', 'Macc.', 'Maced.',
                 'mach.', 'Madag.', 'mag.', 'Man.', 'manuf.', 'Mar.', 'March.', 'marg.', 'masc.', 'math.', 'Matt.',
                 'max.', 'Md.', 'Me.', 'mech.', 'med.', 'Medit.', 'mem.', 'met.', 'metal.', 'metaph.', 'meteorol.',
                 'mfd.', 'mi.', 'Mic.', 'Mich.', 'mycol.', 'Mid.', 'mil.', 'milit.', 'min.', 'mineral.', 'Minn.',
                 'misc.', 'Miss.', 'myth.', 'mk.', 'mkt.', 'ml.', 'MM.', 'Mo.', 'mod.', 'Moham.', 'mol.', 'Mon.',
                 'Mont.', 'Mr.', 'Mrs.', 'MS.', 'Msgr.', 'Mt.', 'mtg.', 'mun.', 'mus.', 'Mus.B.', 'N.', 'N.A.', 'N.B.',
                 'N.C.', 'N.C.O.', 'n.d.', 'N.F.', 'N.G.', 'N.I.', 'N.Y.', 'N.Y.C.', 'N.J.', 'n.p.', 'N.S.', 'N.S.W.',
                 'N.T.', 'N.U.T.', 'N.W.T.', 'N.Z.', 'Nah.', 'natl.', 'naut.', 'nav.', 'navig.', 'Nebr.', 'Neh.',
                 'Neth.', 'neut.', 'Nev.', 'nom.', 'Nor.', 'Norw.', 'Nov.', 'nr.', 'numis.', 'O.', 'O.B.', 'O.C.',
                 'O.D.', 'o.e.', 'O.E.D.', 'O.F.M.', 'O.G.', 'O.P.', 'o.r.', 'O.S.', 'O.S.A.', 'O.S.B.', 'O.S.D.',
                 'O.S.F.', 'O.T.C.', 'ob.', 'Obad.', 'obb.', 'obdt.', 'obj.', 'obs.', 'obstet.', 'Oc.', 'occas.',
                 'oceanog.', 'Oct.', 'off.', 'Okla.', 'Om.', 'Ont.', 'op.', 'opp.', 'orch.', 'ord.', 'ordn.', 'Oreg.',
                 'org.', 'orig.', 'ornithol.', 'Orth.', 'oz.', 'P.', 'P.A.', 'P.B.', 'P.C.', 'P.D.', 'P.E.', 'P.E.I.',
                 'P.G.', 'P.I.', 'P.M.', 'P.M.G.', 'P.O.', 'P.O.D.', 'P.P.', 'p.q.', 'P.R.', 'p.r.n.', 'P.S.', 'P.T.',
                 'P.T.O.', 'P.W.D.', 'Pa.', 'payt.', 'Pal.', 'palaeontol.', 'pam.', 'Pan.', 'par.', 'Parl.', 'part.',
                 'pass.', 'pat.', 'pathol.', 'pc.', 'pct.', 'pd.', 'ped.', 'Pen.', 'Penn.', 'per.', 'pert.', 'Pet.',
                 'petrog.', 'petrol.', 'pf.', 'Pg.', 'Phil.', 'Philem.', 'philol.', 'philos.', 'phys.', 'phon.',
                 'phonol.', 'phot.', 'photom.', 'phr.', 'phren.', 'pizz.', 'pk.', 'pkg.', 'pkt.', 'pl.', 'plat.',
                 'plur.', 'pm.', 'poet.', 'Pol.', 'polit.', 'Port.', 'pos.', 'poss.', 'pot.', 'pp.', 'ppd.', 'Pr.',
                 'pred.', 'pref.', 'prelim.', 'prem.', 'prep.', 'Pres.', 'Presb.', 'pret.', 'prim.', 'priv.', 'prob.',
                 'proc.', 'prod.', 'Prog.', 'prom.', 'pron.', 'prop.', 'propr.', 'pros.', 'Prot.', 'Prov.', 'prox.',
                 'prs.', 'Prus.', 'Ps.', 'pseud.', 'psychoanal.', 'psychol.', 'pt.', 'ptg.', 'pts.', 'pub.', 'publ.',
                 'Pvt.', 'pwt.', 'Q.', 'Q.C.', 'q.e.', 'Q.E.D.', 'Q.E.F.', 'Q.F.', 'q.t.', 'q.v.', 'ql.', 'Qq.', 'qr.',
                 'qt.', 'qto.', 'qu.', 'quad.', 'quart.', 'Que.', 'ques.', 'quot.', 'R.', 'R.A.', 'R.A.A.F.', 'R.A.M.',
                 'R.C.', 'R.C.A.F.', 'R.C.M.P.', 'R.C.P.', 'R.C.S.', 'R.E.', 'r.h.', 'R.I.', 'R.I.B.A.', 'R.I.P.',
                 'R.M.A.', 'R.M.S.', 'R.N.', 'r.p.s.', 'R.Q.', 'R.R.', 'R.S.V.P.', 'rad.', 'rall.', 'rcd.', 'rcpt.',
                 'Rd.', 'Re.', 'rect.', 'redupl.', 'ref.', 'refl.', 'Reg.', 'Regt.', 'rel.', 'Rep.', 'rept.', 'req.',
                 'resp.', 'retd.', 'Rev.', 'rheo.', 'rhet.', 'rit.', 'riv.', 'rm.', 'Rom.', 'rpt.', 'Rs.', 'rt.',
                 'Rus.', 'Russ.', 'Rwy.', 'S.', 's.a.', 'S.D.', 's.g.', 'S.J.', 'S.J.D.', 's.l.', 'S.M.', 's.o.',
                 'S.P.', 'S.R.O.', 'S.T.D.', 'S.W.A.', 'S.W.G.', 'Sab.', 'Sam.', 'Sans.', 'Sask.', 'Sat.', 'Sax.',
                 'sb.', 'sc.', 'sch.', 'sci.', 'Scot.', 'scr.', 'Script.', 'sculp.', 'sd.', 'sec.', 'sect.', 'Sem.',
                 'Sept.', 'seqq.', 'sgd.', 'shpt.', 'shr.', 'shtg.', 'Sig.', 'sym.', 'synd.', 'sing.', 'synop.', 'Syr.',
                 'syst.', 'sld.', 'So.', 'sociol.', 'Sol.', 'Sp.', 'spec.', 'spp.', 'Sq.', 'sqq.', 'Sr.', 'Sra.',
                 'Srta.', 'ss.', 'St.', 'stacc.', 'stat.', 'std.', 'Ste.', 'ster.', 'stg.', 'stge.', 'str.', 'subj.',
                 'Suffr.', 'superl.', 'supp.', 'Supt.', 'surg.', 'surv.', 'Sw.', 'Switz.', 't.', 't.b.', 't.g.',
                 'T.H.I.', 'tab.', 'tbs.', 'tech.', 'teleg.', 'temp.', 'ten.', 'Tenn.', 'ter.', 'term.', 'terr.',
                 'Teut.', 'Tex.', 'Th.B.', 'Th.D.', 'theol.', 'Thess.', 'Thurs.', 'tinct.', 'typ.', 'typw.', 'Tit.',
                 'Tob.', 'topog.', 'tox.', 'tr.', 'trans.', 'transf.', 'transl.', 'transp.', 'trig.', 'Tu.', 'Turk.',
                 'U.', 'U.A.R.', 'U.C.', 'U.K.', 'U.S.', 'U.S.A.', 'U.S.S.', 'U.V.', 'Ukr.', 'Unit.', 'Univ.', 'Uru.',
                 'V.', 'V.A.', 'V.C.', 'v.d.', 'v.g.', 'V.I.', 'V.P.', 'V.R.', 'v.s.', 'v.v.', 'V.W.', 'Va.', 'val.',
                 'var.', 'Vat.', 'vb.', 'vel.', 'Ven.', 'vet.', 'Vic.', 'vil.', 'viz.', 'vo.', 'voc.', 'vols.', 'vs.',
                 'Vt.', 'Vul.', 'Vulg.', 'vv.', 'W.', 'W.A.', 'w.b.', 'W.C.', 'W.C.T.U.', 'W.D.', 'w.f.', 'W.I.',
                 'w.l.', 'W.O.', 'Wal.', 'Wash.', 'wd.', 'whf.', 'whsle.', 'Wyo.', 'Wis.', 'Wisd.', 'wk.', 'wkly.',
                 'wmk.', 'Xn.', 'Xnty.', 'Xt.', 'z.', 'Zech.', 'Zeph.', 'zool.'}

dataset = [("abstract", "Antonym", "concrete"),
               ("accident", "Antonym", "plan"),
               ("accident", "Antonym", "purpose"),
               ("accident", "Synonym", "event"),
               ("accident", "IsA", "error"),
               ("accident", "IsA", "happen"),
               ("accident", "IsA", "mistake"),
               ("account", "Synonym", "record"),
               ("account", "Synonym", "report"),
               ("account", "Synonym", "score"),
               ("account", "Synonym", "statement"),
               ("account", "IsA", "pay"),
               ("act", "HasProperty", "fun"),
               ("act", "Antonym", "nothing"),
               ("act", "Antonym", "real"),
               ("act", "Synonym", "action"),
               ("act", "Synonym", "performance"),
               ("act", "IsA", "art"),
               ("act", "IsA", "communication"),
               ("act", "IsA", "drama"),
               ("act", "IsA", "perform"),
               ("act", "IsA", "performance"),
               ("act", "IsA", "pretend"),
               ("act", "PartOf", "performance"),
               ("act", "PartOf", "play"),
               ("action", "HasProperty", "excite"),
               ("action", "Synonym", "battle"),
               ("action", "Synonym", "conflict"),
               ("action", "Synonym", "energy"),
               ("action", "Synonym", "exercise"),
               ("action", "Synonym", "movement"),
               ("action", "Synonym", "performance"),
               ("action", "Synonym", "play"),
               ("action", "Synonym", "plot"),
               ("action", "Synonym", "prosecution"),
               ("action", "IsA", "act"),
               ("action", "IsA", "event"),
               ("action", "IsA", "play"),
               ("action", "IsA", "work"),
               ("active", "Antonym", "quiet"),
               ("active", "Antonym", "slow"),
               ("active", "Synonym", "busy"),
               ("active", "Synonym", "work"),
               ("active", "IsA", "person"),
               ("actor", "Synonym", "actress"),
               ("actor", "IsA", "person"),
               ("actor", "PartOf", "film"),
               ("actress", "Antonym", "actor"),
               ("actress", "IsA", "human"),
               ("actress", "IsA", "person"),
               ("add", "Antonym", "remove"),
               ("add", "Antonym", "take"),
               ("add", "Antonym", "take_away"),
               ("add", "Synonym", "join"),
               ("add", "IsA", "increase"),
               ("address", "PartOf", "letter"),
               ("address", "Entails", "speak"),
               ("admire", "Antonym", "dislike"),
               ("admire", "IsA", "look"),
               ("admire", "IsA", "respect"),
               ("adore", "IsA", "love"),
               ("adult", "Antonym", "child"),
               ("adult", "Synonym", "grow_up"),
               ("adult", "IsA", "animal"),
               ("adult", "IsA", "person"),
               ("advance", "Antonym", "back"),
               ("advance", "Antonym", "fall"),
               ("advance", "Antonym", "late"),
               ("advance", "Synonym", "improve"),
               ("advance", "IsA", "increase"),
               ("advance", "IsA", "move"),
               ("adventure", "HasProperty", "thrill"),
               ("adventure", "Antonym", "boredom"),
               ("adventure", "Antonym", "home"),
               ("adventure", "Antonym", "lazy"),
               ("adventure", "Antonym", "nothing"),
               ("adventure", "Antonym", "safe"),
               ("adventure", "IsA", "action"),
               ("adventure", "IsA", "game"),
               ("aeroplane", "HasProperty", "fly"),
               ("aeroplane", "HasA", "seat"),
               ("affair", "Antonym", "marriage"),
               ("affair", "Antonym", "spouse"),
               ("affection", "HasProperty", "healthy"),
               ("affection", "Antonym", "dislike"),
               ("affection", "Synonym", "love"),
               ("affection", "IsA", "feel"),
               ("affection", "IsA", "like"),
               ("age", "Antonym", "young"),
               ("age", "Synonym", "historic_period"),
               ("age", "IsA", "change"),
               ("age", "IsA", "develop"),
               ("age", "PartOf", "life"),
               ("agreement", "HasProperty", "good"),
               ("agreement", "Synonym", "contract"),
               ("agreement", "Synonym", "deal"),
               ("agreement", "Synonym", "understand"),
               ("agreement", "IsA", "statement"),
               ("aid", "Synonym", "help"),
               ("aid", "Synonym", "support"),
               ("air", "HasProperty", "clear"),
               ("air", "HasProperty", "free"),
               ("air", "Antonym", "earth"),
               ("air", "Antonym", "land"),
               ("air", "Antonym", "vacuum"),
               ("air", "Antonym", "water"),
               ("air", "Synonym", "atmosphere"),
               ("air", "HasA", "oxygen"),
               ("air", "HasA", "pressure"),
               ("air", "HasA", "weight"),
               ("air", "IsA", "gas"),
               ("air", "MadeOf", "gas"),
               ("air", "MadeOf", "molecule"),
               ("air", "MadeOf", "oxygen"),
               ("airplane", "HasProperty", "fun"),
               ("airplane", "HasProperty", "heavy"),
               ("airplane", "HasA", "wheel"),
               ("airplane", "HasA", "wing"),
               ("airplane", "IsA", "machine"),
               ("airplane", "IsA", "transportation"),
               ("aisle", "Antonym", "seat"),
               ("aisle", "IsA", "passageway"),
               ("aisle", "PartOf", "store"),
               ("alabama", "IsA", "place"),
               ("alarm", "HasProperty", "loud"),
               ("album", "Synonym", "disk"),
               ("album", "MadeOf", "vinyl"),
               ("alcohol", "HasProperty", "fun"),
               ("alcohol", "Antonym", "water"),
               ("alcohol", "IsA", "drug"),
               ("alcohol", "MadeOf", "rice"),
               ("alcoholic", "IsA", "human"),
               ("all", "Antonym", "nobody"),
               ("all", "Antonym", "nothing"),
               ("alley", "HasProperty", "dark"),
               ("alley", "Synonym", "aisle"),
               ("alley", "Synonym", "walk"),
               ("alley", "IsA", "street"),
               ("alphabet", "Antonym", "number"),
               ("alto", "IsA", "pitch"),
               ("aluminium", "Antonym", "tin"),
               ("aluminium", "Synonym", "aluminum"),
               ("aluminum", "IsA", "gray"),
               ("aluminum", "IsA", "material"),
               ("america", "HasProperty", "huge"),
               ("america", "HasProperty", "violent"),
               ("america", "HasA", "beach"),
               ("america", "HasA", "flag"),
               ("america", "HasA", "president"),
               ("america", "IsA", "continent"),
               ("america", "IsA", "country"),
               ("america", "IsA", "democracy"),
               ("america", "IsA", "place"),
               ("america", "PartOf", "world"),
               ("anchor", "MadeOf", "iron"),
               ("anchor", "PartOf", "vessel"),
               ("angel", "HasProperty", "good"),
               ("angel", "HasA", "wing"),
               ("angel", "IsA", "person"),
               ("anger", "HasProperty", "unpleasant"),
               ("anger", "Antonym", "calm"),
               ("anger", "Antonym", "happiness"),
               ("anger", "Antonym", "happy"),
               ("anger", "Antonym", "love"),
               ("anger", "Synonym", "enrage"),
               ("anger", "IsA", "feel"),
               ("animal", "HasProperty", "alive"),
               ("animal", "HasProperty", "friendly"),
               ("animal", "HasProperty", "pure"),
               ("animal", "Antonym", "bug"),
               ("animal", "Antonym", "human"),
               ("animal", "Antonym", "mineral"),
               ("animal", "Antonym", "person"),
               ("animal", "Antonym", "plant"),
               ("animal", "Antonym", "vegetable"),
               ("animal", "HasA", "baby"),
               ("animal", "HasA", "body"),
               ("animal", "HasA", "bone"),
               ("animal", "HasA", "emotion"),
               ("animal", "HasA", "eye"),
               ("animal", "HasA", "fur"),
               ("animal", "HasA", "meat"),
               ("animal", "HasA", "muscle"),
               ("animal", "HasA", "pain"),
               ("animal", "IsA", "life"),
               ("animal", "IsA", "organism"),
               ("animal", "PartOf", "nature"),
               ("animate", "Antonym", "stationary"),
               ("annoy", "HasProperty", "bad"),
               ("annoy", "Antonym", "please"),
               ("answer", "Antonym", "problem"),
               ("answer", "Antonym", "question"),
               ("answer", "Antonym", "unknown"),
               ("answer", "IsA", "statement"),
               ("antique", "HasProperty", "old"),
               ("antique", "HasProperty", "valuable"),
               ("antique", "HasProperty", "value"),
               ("antique", "Antonym", "new"),
               ("apartment", "HasProperty", "black"),
               ("apartment", "HasProperty", "red"),
               ("apartment", "Synonym", "flat"),
               ("apartment", "HasA", "door"),
               ("apartment", "HasA", "kitchen"),
               ("apartment", "IsA", "build"),
               ("apartment", "IsA", "home"),
               ("apartment", "IsA", "house"),
               ("appear", "Antonym", "leave"),
               ("appear", "Synonym", "arrive"),
               ("appear", "Synonym", "be"),
               ("appear", "Synonym", "come"),
               ("appear", "Synonym", "look"),
               ("appear", "Synonym", "present"),
               ("appear", "Synonym", "show"),
               ("appear", "IsA", "perform"),
               ("apple", "HasProperty", "alive"),
               ("apple", "HasProperty", "good"),
               ("apple", "HasProperty", "green"),
               ("apple", "HasProperty", "healthy"),
               ("apple", "HasProperty", "red"),
               ("apple", "HasProperty", "small"),
               ("apple", "HasProperty", "sweet"),
               ("apple", "HasProperty", "tasty"),
               ("apple", "HasProperty", "yellow"),
               ("apple", "Antonym", "orange"),
               ("apple", "HasA", "core"),
               ("apple", "HasA", "juice"),
               ("apple", "HasA", "peel"),
               ("apple", "HasA", "seed"),
               ("apple", "HasA", "skin"),
               ("apple", "IsA", "computer"),
               ("apple", "IsA", "tree"),
               ("apple", "PartOf", "core"),
               ("approach", "Synonym", "advance"),
               ("approach", "IsA", "address"),
               ("approach", "IsA", "come"),
               ("approach", "IsA", "movement"),
               ("approach", "Entails", "advance"),
               ("arch", "IsA", "bend"),
               ("arch", "IsA", "build"),
               ("arch", "IsA", "form"),
               ("arch", "IsA", "open"),
               ("arch", "PartOf", "bridge"),
               ("arch", "PartOf", "wall"),
               ("argument", "PartOf", "conclusion"),
               ("arise", "Antonym", "get_down"),
               ("arithmetic", "Synonym", "math"),
               ("arithmetic", "IsA", "math"),
               ("arm", "Antonym", "leg"),
               ("arm", "PartOf", "body"),
               ("arm", "PartOf", "human"),
               ("arm", "PartOf", "person"),
               ("armchair", "HasProperty", "comfortable"),
               ("armchair", "HasA", "back"),
               ("armor", "Antonym", "clothe"),
               ("armor", "Synonym", "plate"),
               ("army", "Antonym", "marine"),
               ("army", "Antonym", "navy"),
               ("army", "IsA", "crowd"),
               ("army", "MadeOf", "soldier"),
               ("army", "PartOf", "war"),
               ("arrange", "IsA", "agree"),
               ("art", "HasProperty", "abstract"),
               ("art", "HasProperty", "beautiful"),
               ("art", "Antonym", "science"),
               ("art", "Antonym", "ugly"),
               ("art", "Synonym", "creation"),
               ("art", "IsA", "creation"),
               ("art", "IsA", "hobby"),
               ("art", "IsA", "play"),
               ("article", "HasA", "news"),
               ("article", "IsA", "piece"),
               ("article", "MadeOf", "information"),
               ("article", "PartOf", "document"),
               ("article", "PartOf", "newspaper"),
               ("artist", "HasProperty", "powerful"),
               ("artist", "IsA", "human"),
               ("artist", "IsA", "person"),
               ("ascend", "Antonym", "descend"),
               ("ascend", "Synonym", "climb"),
               ("ascend", "Synonym", "rise"),
               ("ascend", "IsA", "change"),
               ("asia", "HasProperty", "large"),
               ("asia", "IsA", "place"),
               ("asia", "PartOf", "earth"),
               ("assemble", "Antonym", "break"),
               ("assemble", "Antonym", "destroy"),
               ("assemble", "IsA", "make"),
               ("athlete", "HasProperty", "energetic"),
               ("athlete", "IsA", "human"),
               ("athlete", "IsA", "person"),
               ("atmosphere", "Synonym", "feel"),
               ("atmosphere", "Synonym", "mood"),
               ("atmosphere", "IsA", "air"),
               ("atmosphere", "PartOf", "sky"),
               ("atom", "HasA", "electron"),
               ("atom", "MadeOf", "neutron"),
               ("atom", "MadeOf", "nucleus"),
               ("atom", "MadeOf", "proton"),
               ("atom", "PartOf", "molecule"),
               ("attach", "Antonym", "separate"),
               ("attach", "Synonym", "connect"),
               ("attach", "Synonym", "fasten"),
               ("attach", "Synonym", "tie"),
               ("attach", "IsA", "connect"),
               ("attach", "IsA", "join"),
               ("attach", "IsA", "touch"),
               ("australia", "IsA", "continent"),
               ("australia", "IsA", "island"),
               ("australia", "IsA", "place"),
               ("author", "Synonym", "artist"),
               ("author", "Synonym", "writer"),
               ("author", "IsA", "person"),
               ("author", "IsA", "write"),
               ("author", "PartOf", "book"),
               ("authority", "IsA", "book"),
               ("automobile", "Synonym", "car"),
               ("automobile", "HasA", "radio"),
               ("automobile", "HasA", "trunk"),
               ("automobile", "MadeOf", "steel"),
               ("awaken", "IsA", "change"),
               ("ax", "MadeOf", "metal"),
               ("axe", "HasProperty", "sharp"),
               ("baby", "HasProperty", "amuse"),
               ("baby", "HasProperty", "entertain"),
               ("baby", "HasProperty", "fragile"),
               ("baby", "HasProperty", "fun"),
               ("baby", "HasProperty", "happy"),
               ("baby", "HasProperty", "innocent"),
               ("baby", "HasProperty", "nice"),
               ("baby", "HasProperty", "satisfy"),
               ("baby", "HasProperty", "small"),
               ("baby", "HasProperty", "smile"),
               ("baby", "HasProperty", "ugly"),
               ("baby", "HasProperty", "young"),
               ("baby", "Antonym", "adult"),
               ("baby", "Antonym", "man"),
               ("baby", "Antonym", "old"),
               ("baby", "Synonym", "love"),
               ("baby", "HasA", "hair"),
               ("baby", "IsA", "child"),
               ("baby", "IsA", "girl"),
               ("baby", "IsA", "mammal"),
               ("baby", "IsA", "person"),
               ("baby", "PartOf", "family"),
               ("back", "Antonym", "main"),
               ("back", "Synonym", "rear"),
               ("back", "Synonym", "reverse"),
               ("back", "IsA", "confirm"),
               ("back", "PartOf", "chair"),
               ("back", "PartOf", "human"),
               ("back", "PartOf", "trunk"),
               ("bacon", "Synonym", "ham"),
               ("bacon", "MadeOf", "pig"),
               ("bad", "Antonym", "benevolent"),
               ("bad", "Antonym", "good"),
               ("bad", "Antonym", "right"),
               ("bad", "Antonym", "superior"),
               ("bad", "Antonym", "true"),
               ("bad", "IsA", "evil"),
               ("bad", "IsA", "quality"),
               ("bad", "IsA", "result"),
               ("bag", "HasProperty", "blue"),
               ("bag", "Synonym", "baggage"),
               ("bag", "MadeOf", "fabric"),
               ("bag", "MadeOf", "plastic"),
               ("baggage", "Synonym", "gear"),
               ("balance", "Antonym", "bias"),
               ("balance", "Antonym", "prejudice"),
               ("balance", "Synonym", "account"),
               ("balance", "Synonym", "scale"),
               ("balance", "IsA", "match"),
               ("balance", "IsA", "scale"),
               ("balance", "PartOf", "account"),
               ("ball", "HasProperty", "black"),
               ("ball", "HasProperty", "fun"),
               ("ball", "Synonym", "globe"),
               ("ball", "IsA", "baseball"),
               ("ball", "IsA", "event"),
               ("ball", "IsA", "sport"),
               ("ball", "IsA", "toy"),
               ("ball", "MadeOf", "plastic"),
               ("ball", "PartOf", "human"),
               ("balloon", "HasProperty", "colorful"),
               ("balloon", "HasProperty", "hollow"),
               ("balloon", "HasProperty", "rubber"),
               ("balloon", "HasA", "air"),
               ("balloon", "HasA", "gas"),
               ("balloon", "HasA", "water"),
               ("balloon", "IsA", "rubber"),
               ("balloon", "IsA", "sport"),
               ("balloon", "MadeOf", "rubber"),
               ("banana", "HasProperty", "green"),
               ("banana", "HasProperty", "yellow"),
               ("banana", "HasA", "peel"),
               ("banana", "IsA", "dessert"),
               ("band", "Synonym", "ring"),
               ("banjo", "IsA", "string_instrument"),
               ("banjo", "MadeOf", "wood"),
               ("bank", "HasA", "change"),
               ("bank", "HasA", "coin"),
               ("bank", "IsA", "place"),
               ("bank", "IsA", "work"),
               ("bar", "IsA", "business"),
               ("bar", "IsA", "place"),
               ("bar", "IsA", "support"),
               ("bar", "PartOf", "court"),
               ("bar", "PartOf", "goal"),
               ("barbecue", "IsA", "cook"),
               ("bark", "HasProperty", "rough"),
               ("bark", "Antonym", "bite"),
               ("bark", "IsA", "noise"),
               ("bark", "IsA", "talk"),
               ("bark", "IsA", "tan"),
               ("bark", "PartOf", "branch"),
               ("bark", "PartOf", "tree"),
               ("bark", "PartOf", "trunk"),
               ("base", "HasProperty", "black"),
               ("base", "Antonym", "top"),
               ("base", "Synonym", "bad"),
               ("base", "PartOf", "baseball_diamond"),
               ("base", "PartOf", "box"),
               ("base", "PartOf", "vessel"),
               ("baseball", "HasProperty", "hard"),
               ("baseball", "HasProperty", "nice"),
               ("baseball", "HasA", "stitch"),
               ("baseball", "IsA", "action"),
               ("baseball", "IsA", "game"),
               ("baseball", "IsA", "hobby"),
               ("baseball", "IsA", "sport"),
               ("baseball_diamond", "IsA", "place"),
               ("basement", "Antonym", "attic"),
               ("basement", "IsA", "place"),
               ("basement", "PartOf", "house"),
               ("basket", "IsA", "container"),
               ("basket", "MadeOf", "plastic"),
               ("basketball", "HasProperty", "cool"),
               ("basketball", "HasProperty", "fun"),
               ("basketball", "HasProperty", "orange"),
               ("basketball", "HasProperty", "sport"),
               ("basketball", "IsA", "game"),
               ("basketball", "IsA", "sport"),
               ("basketball", "PartOf", "game"),
               ("bat", "Synonym", "baseball_bat"),
               ("bat", "HasA", "eye"),
               ("bat", "HasA", "wing"),
               ("bat", "IsA", "animal"),
               ("bat", "IsA", "club"),
               ("bat", "IsA", "hit"),
               ("bat", "IsA", "stuff"),
               ("bath", "HasProperty", "relax"),
               ("bath", "Antonym", "shower"),
               ("bath", "HasA", "water"),
               ("bath", "IsA", "place"),
               ("bathroom", "HasProperty", "dark"),
               ("bathroom", "Synonym", "bath"),
               ("bathroom", "HasA", "bath"),
               ("bathroom", "HasA", "ceiling"),
               ("bathroom", "HasA", "plumb"),
               ("bathroom", "HasA", "sink"),
               ("bathroom", "HasA", "toilet"),
               ("bathroom", "IsA", "place"),
               ("bathroom", "PartOf", "dwell"),
               ("bathroom", "PartOf", "house"),
               ("bathtub", "Synonym", "bath"),
               ("bathtub", "IsA", "vessel"),
               ("bathtub", "PartOf", "bathroom"),
               ("battle", "Antonym", "peace"),
               ("battle", "Synonym", "conflict"),
               ("battle", "IsA", "fight"),
               ("battle", "PartOf", "war"),
               ("be", "IsA", "state"),
               ("be_alone", "IsA", "choice"),
               ("beach", "HasProperty", "nice"),
               ("beach", "HasProperty", "white"),
               ("beach", "HasA", "sand"),
               ("beach", "IsA", "place"),
               ("beach", "IsA", "shore"),
               ("beach", "MadeOf", "sand"),
               ("beach", "PartOf", "shore"),
               ("beak", "IsA", "body_part"),
               ("beak", "IsA", "mouth"),
               ("beak", "IsA", "nose"),
               ("beak", "PartOf", "bird"),
               ("beam", "Synonym", "smile"),
               ("beam", "IsA", "light"),
               ("bean", "IsA", "film"),
               ("bear", "Antonym", "lion"),
               ("bear", "Synonym", "birth"),
               ("bear", "HasA", "claw"),
               ("bear", "HasA", "fur"),
               ("beat", "Synonym", "hammer"),
               ("beat", "IsA", "move"),
               ("beat", "Entails", "hit"),
               ("beat", "Entails", "win"),
               ("beautiful", "Antonym", "bad"),
               ("beautiful", "Antonym", "dull"),
               ("beautiful", "Antonym", "nasty"),
               ("beautiful", "Antonym", "plain"),
               ("beautiful", "Antonym", "ugly"),
               ("beauty", "HasProperty", "rare"),
               ("beauty", "Antonym", "ugly"),
               ("beauty", "IsA", "person"),
               ("bed", "HasProperty", "big"),
               ("bed", "HasProperty", "comfortable"),
               ("bed", "HasProperty", "flat"),
               ("bed", "HasProperty", "fun"),
               ("bed", "HasProperty", "soft"),
               ("bed", "HasProperty", "square"),
               ("bed", "Antonym", "bath"),
               ("bed", "Antonym", "chair"),
               ("bed", "Antonym", "sofa"),
               ("bed", "IsA", "device")]
